trigger:
- main  # Run pipeline on push to 'main' branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- script: |
    git clone https://github.com/Kianni/memowo-be.git
  displayName: 'Clone Backend Repository'

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    echo "REACT_APP_BACKEND_URL=https://memowo-be-cddfeyawhfegd2b9.canadaeast-01.azurewebsites.net/graphql" > .env
    npm install
  displayName: 'Install Frontend Dependencies'

- script: |
    cd ./memowo-be
    npm install
  displayName: 'Install Backend Dependencies'

- script: |
    cd ./memowo-be
    npm start &
    npx wait-on http://localhost:4000
    echo "Backend server is up and running"
    curl -I http://localhost:4000
  displayName: 'Start and Verify Backend Server'

- script: |
    npm start &
    npx wait-on http://localhost:3000
    echo "Frontend server is up and running"
    curl -I http://localhost:3000
  displayName: 'Start and Verify Frontend Server'
  
- script: |
    CI=true npm test -- --watchAll=false
  displayName: 'Run Tests'

- script: |
    npx cypress install
  displayName: 'Install Cypress'

- script: |
    npx cypress run
  displayName: 'Run Cypress Integration Tests'

- script: |
    npm run build
  displayName: 'Build App'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/build.zip'
  displayName: 'Archive Build Folder'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureForStudentsConnection'
    appType: 'webAppLinux'  # Specify that this is a Linux-based Web App
    appName: 'memowo-fe'
    package: '$(Build.ArtifactStagingDirectory)/build.zip'
    startupCommand: 'npx serve -s .'
  displayName: 'Deploy React App to Azure'
